### ISSUE TITLE
Kong 1.2RC2 - Failure to change GET to POST and add request body

### ISSUE THREAD

**Issue by rsbrisci** [Kong/kong-plugin-request-transformer#1]
Issue is that new version of Request Transformer plugin cannot change a GET to a POST & add a body.

## SETUP
Create a proxy with request transformer plugin enabled
Set Method: POST
ADD Header: `Content-Type:application/json`
ADD BODY: `body:true`

## TEST
Send GET with no `Content-Type` header to proxy

**Expectation:** Upstream will receive a POST with Content-Type `application/json` and body `{"body":"true"}`

**Observation:** Upstream receives a POST with no body

The exact same test with the same client/configs/everything succeeds on Kong 1.0.3

## My plugin configs (not all involved in this issue)
```
{
  "created_at": 1550864463,
  "config": {
    "remove": {
      "querystring": [],
      "headers": [
        "x-testcase-remove"
      ],
      "body": []
    },
    "replace": {
      "querystring": [],
      "headers": [
        "x-testcase-replace:true"
      ],
      "body": [],
      "uri": null
    },
    "http_method": "POST",
    "append": {
      "querystring": [],
      "headers": [
        "x-testcase-append:stargate"
      ],
      "body": []
    },
    "add": {
      "querystring": [],
      "headers": [
        "x-testcase-add:true",
        "Content-Type:application/json"
      ],
      "body": [
        "body:true"
      ]
    },
    "rename": {
      "querystring": [],
      "headers": [
        "x-rename-me:x-stargate-rename"
      ],
      "body": []
    }
  },
  "id": "3c43e872-3d84-430c-88d5-7d14050960f8",
  "service": null,
  "name": "request-transformer",
  "enabled": true,
  "route": {
    "id": "b4a039a5-d9ff-4294-ba09-676a2a716d3f"
  },
  "run_on": "first",
  "consumer": null,
  "protocols": [
    "http",
    "https"
  ],
  "tags": null
}
```

**Comment by gszr** [comment]
@rsbrisci Thank you for the report; the fix is merged and will be in Kong 1.2.1 -- to be released later this week.
