### ISSUE TITLE
Unable to set X-Forwarded-* headers

### ISSUE THREAD

**Issue by trollr** [Kong/kong-plugin-request-transformer#17]
Nginx always overrides X-Forwarded-* headers. 

Possible Solutions: 

- Write in in the docs and live with it
- Add an variable which will set to true if request transformer changed headers to forbid another change

**Comment by hishamhm** [comment]
@trollr Thanks for the report! Yes, at the very least we need to document this behavior. We'll look into doing that.

**Comment by trollr** [comment]
Just for interest: Are there any valid reasons why request-transformer is not allowed to override x-forwarded-* headers? 

I use a kong ingress setup in a kubernetes cluster and a proxied service do csrf protection. Im not able to change x-forwarded-port header. That's the reason Im not able to use the service -.-

**Comment by trollr** [comment]
Post functions allow to overwrite x-forwarded-* header see https://github.com/Kong/kong/issues/5559
