### ISSUE TITLE
How to execute request-transformer in both Service, Route and Consumer?

### ISSUE THREAD

**Issue by allanc85** [Kong/kong-plugin-request-transformer#18]
Hello,

I'm trying to add a header param in both Service, Route and Consumer, but it appear that only one is executed.
It seams the order is: Consumer > Route > Service

---

### **How to reproduce:**
_PS: To make it easy, I'm returning all headers params in a test api_

`kong version: 2.0.2`

Add request-transformer to Service:
```
curl -X POST http://localhost:8001/services/c5f74a30-a5ef-41c8-b64d-82420de50cb7/plugins \
    --data "name=request-transformer"  \
    --data "config.add.headers=service-id:c5f74a30-a5ef-41c8-b64d-82420de50cb7"
```
service-id is returned:
![Screen Shot 2020-03-14 at 18 34 11](https://user-images.githubusercontent.com/1746994/76690783-8c7aca00-6622-11ea-9658-29db4d16edea.png)

After, we add request-transformer to Route:
```
curl -X POST http://localhost:8001/routes/dfe31c20-a17f-4921-9e7b-8dc936d75314/plugins \
    --data "name=request-transformer"  \
    --data "config.add.headers=route-id:dfe31c20-a17f-4921-9e7b-8dc936d75314"
```
Route-id is returned, but it did not add the service-id:
![Screen Shot 2020-03-14 at 18 34 25](https://user-images.githubusercontent.com/1746994/76690784-91d81480-6622-11ea-898f-825021077a81.png)

The same occur when adding it to Consumer (the consumer-id is already returned in X-Consumer-Id param, it's just an example):
```
curl -X POST http://localhost:8001/consumers/334027b6-f818-46fb-bda3-44e05561bbef/plugins \
    --data "name=request-transformer" \
    --data "config.add.headers=consumer-id:334027b6-f818-46fb-bda3-44e05561bbef"
```
Only consumer-id is returned, the consumer-id and route-id are not added.
![Screen Shot 2020-03-14 at 18 34 38](https://user-images.githubusercontent.com/1746994/76690787-969cc880-6622-11ea-802a-6882d5278324.png)

It seems only one transformer is executed, is that correct?
Is it possible to add params in more than one entity with the plugin?

Thanks

**Comment by hishamhm** [comment]
@allanc85 The behavior described above is working as intended — this is a limitation of the current plugin execution model, which is unfortunate for your use-case. It is useful for other scenarios, though: for example, in rate-limiting plugins, you may want to have different limits by service in general and for a specific consumer, but not want the general limit to be applied to the specific consumer.

We wish to extend the plugin model in the future to make it more flexible so it can deal with both the rate-limiting use-case described above and the one you described in this issue, but currently this is not possible.

**Comment by allanc85** [comment]
@hishamhm ,
Thanks for your answer and your time to write it clearly.
It also helped me to understand better how plugins work.

Best regards,
