### ISSUE TITLE
body transformation

### ISSUE THREAD

**Issue by ruslanruslanruslan** [Kong/kong-plugin-request-transformer#31]
May you share please an example how to transform request body?
My goal is to take body, add some symbols in the beginning and in the end
for example: 
{"val"="1"}  ==>>  {record:[{"val"="1"}]}

**Comment by locao** [comment]
Hi @ruslanruslanruslan! You can check the request-transformer plugins docs here: https://docs.konghq.com/hub/kong-inc/request-transformer/

This configuration depends a lot on what inputs you are expecting to receive. It is possible that you will need to use templating feature.

Also, you can share your experience in [Kong Nation](https://discuss.konghq.com/), other users might have insights to help you with that.

**Comment by ruslanruslanruslan** [comment]
@locao 
if you open docs link that you provided, you will see that there is no ability to change body. 
Same way with templates, they work with header, url, query, but not with body.
