### ISSUE TITLE
unable to rename header 

### ISSUE THREAD

**Issue by issambaccouch** [Kong/kong-plugin-request-transformer#43]
i want to rename my api key header from api-key to apikey with this request 

`curl -X POST http://localhost:8001/plugins \
    --data "name=request-transformer" \
    --data-urlencode "config.rename.headers=apikey:\$(headers['api-key'] or 'api-key')" \
    --data "config.remove.headers=api-key"`
    
but i am getting error 

`{"message":"schema violation (config.rename: {\n  headers = {\n    \"'$(headers['api-key'] or 'api-key')' is not a valid header\"\n  }\n})","name":"schema violation","fields":{"config":{"rename":{"headers":["'$(headers['api-key'] or 'api-key')' is not a valid header"]}}},"code":2}`

any suggestion to solve this issue thank you

**Comment by locao** [comment]
Hi @issambaccouch! If you want to rename `api-key` to `apikey` you need only `--data "config.rename.headers=api-key=apikey"`, there's no need to use templates or removing the header afterward.
